
###
GET http://localhost:3000/
Accept: application/json

###
POST https://newer_news_server.paas-ta.org/api/signup
Accept: application/json
content-Type: application/json

{
  "user": {
    "email": "test2@gmail.com",
    "password": "test123",
    "username": "gill"
  }
}

###
POST http://localhost:3000/api/login
Accept: application/json
content-Type: application/json

{

    "email": "test2@gmail.com",
    "password": "test123"

}

