# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to cloudfoundry
        uses: comsysto/cloudfoundry-action/auth@v1.0
        with:
          api: 'https://api.paas-ta.org'
          user: ${{ secrets.CF_USER }}
          password: ${{ secrets.CF_PASSWORD }}
      - name: Switch to cf org and space
        uses: comsysto/cloudfoundry-action/cli@v1.0
        with:
          args: target -o 'nonuknuk' -s 'dev'
      - name: cf push
        uses: comsysto/cloudfoundry-action/cli@v1.0
        with:
          args: push newer_news_server -b https://github.com/cloudfoundry/ruby-buildpack.git -f ./manifest.yml
