# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: elliottpope/cloudfoundry-cli-action@v7
          with:
            CF_API: https://api.my-cloud-foundry.com
            USERNAME: ${{ secrets.CF_USER }}
            PASSWORD: ${{ secrets.CF_PASSWORD }}
            ORG: nonuknuk
            SPACE: dev
            COMMAND: push newer_news_server -b https://github.com/cloudfoundry/ruby-buildpack.git\#v1.8.48
