name: Deploy to Cloud Foundry

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    # Build your app here

  deploy:
    runs-on: ubuntu-18.04
    needs: build
    
    steps:
    - uses: citizen-of-planet-earth/cf-cli-action@master
      with:
        cf_api: https://api.paas-ta.org
        cf_username: ${{ secrets.CF_USER }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        cf_space: Dev
        command: cf push -b https://github.com/cloudfoundry/ruby-buildpack.git
